# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: composectl

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: composectl
    binary: composectl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w
      - -X github.com/kreigan/adm-composectl/cmd.version={{.Version}}

archives:
  - id: binary
    formats:
      - binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: 'Other'
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: kreigan
    name: adm-composectl
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
